### ISSUE TITLE
Chrome result of css-text-shaping will be improved vastly in Version 76

### ISSUE THREAD

**Issue by ebraminio** [w3c/i18n-tests#21]
If everything goes according to the plan https://w3c.github.io/i18n-tests/results/css-text-shaping Chrome result will be vastly improved by Jul 30 with Chrome 76 release per https://www.chromestatus.com/features/schedule I've filled this as a placeholder for the PR and notifying you here about it. It is however not perfect yet, https://crbug.com/939533 for example. One easily can test the feature even in older versions by enabling LayoutNG in about:flags of Chrome. It will become even better than Firefox in some regards so may Firefox now should also go for improvements on things like shaping across weights of the same font.

**Comment by r12a** [comment]
@ebraminio sorry to take so long, but the results page is now updated. Lot's of the tests now pass, which is great.  Unfortunately, some still fail where joining forms are not expected.

Please feel free to reopen this issue if you want to discuss, or raise a new issue. Thanks!
