### ISSUE TITLE
Counter-styles tests broken

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-tests#31]
https://w3c.github.io/i18n-tests/results/custom-counter-styles

I believe these worked fine originally, but for some reason they no longer do.  In Firefox the test and ref appear to be using different fonts.

The easiest way to fix this is to remove the content of the support/create.ref function, which will make the list marker and the content appear side by side. 

Since that fix makes it much harder to check that all is correct, perhaps we could figure out how to make the overaly approach work?  I spent some time on it this morning, but drew a blank.  @xfq @himorin any ideas?

**Comment by himorin** [comment]
sorry to ask this kind of thing, but do you have specific one? Using Firefox 81.0, I could not find one which should pass (by means, marked as implemented/supported in caniuse etc.) but show red part...

**Comment by r12a** [comment]
Here's what i see for the very first one, and for many others (using FF 80).

![Screenshot 2020-09-23 at 10 35 20](https://user-images.githubusercontent.com/4839211/93995213-a2fb9e00-fd88-11ea-85cd-347fbf4ef168.png)

In this case, the overlap is fixed by assigning lang="ar" to the encapsulating div, but that doesn't work completely for the Farsi test that follows (ie. when setting lang to fa).  It also introduces some font fallback issues on my system.

**Comment by himorin** [comment]
it's my capture on Windows10/Firefox 81.0 (was the same for 80.0.6 on backup).

![image](https://user-images.githubusercontent.com/3918572/94070340-fc1d0d80-fe2c-11ea-825b-18c94e7eb5ef.png)

both red text and li::marker say these are rendered using 'Times New Roman'. I think no additional arabic font (than OS default in Japanese edition) installed on the Windows.

**Comment by xfq** [comment]
FWIW, my result is the same as Atsushi's (in Firefox 81.0 on macOS 10.15.6).

**Comment by r12a** [comment]
This no longer seems problematic for me, so closing.
